-----------------------------------------
-- 4. EVOLUCION DEL PRONOSTICO Y BENEFICIO REAL: ESTUDIO DE TRAYECTORIA POR CATEGORIA
-----------------------------------------
SELECT
    COALESCE(S.CATEGORY, F.CATEGORY)   		AS CATEGORIA,
    SUM(S.PROFIT)                        	AS BENEFICIO,
    SUM(F.FORECAST)                       	AS PREVISION_BENEFICIO,
    MIN(F.OPPORTUNITY_AGE)            		AS OPORTUNIDAD_MAS_RECIENTE,
    MAX(F.OPPORTUNITY_AGE)          		AS OPORTUNIDAD_MAS_ANTIGUA
FROM SALES S 			FULL OUTER JOIN FORECASTS F
    ON S.CATEGORY = F.CATEGORY
   AND S.YEAR = F.YEAR
WHERE (S.YEAR = 2021 OR F.YEAR = 2022)
GROUP BY COALESCE(S.CATEGORY, F.CATEGORY)
ORDER BY CATEGORIA
;
