-----------------------------------------
--#3. ESTUDIO DE INDUSTRIAS GENERAN MAYOR BENEFICIO EN ETAPA DE COMPROMISO "COMMIT"
-----------------------------------------
SELECT
    A.INDUSTRY                  	AS INDUSTRY,
    SUM(S.PROFIT)               	AS TOTAL_PROFIT,
    CASE
        WHEN SUM(S.PROFIT) > 1000000 THEN 'ALTO'
        ELSE 'NORMAL'
    END 				AS PROFIT_CATEGORY
FROM SALES AS S 		JOIN ACCOUNTS AS A
    ON S.ACCOUNT = A.ACCOUNT
WHERE S.ACCOUNT IN (
    SELECT DISTINCT F.ACCOUNT, 
    FROM FORECASTS AS F
    WHERE F.PREDICTION_CATEGORY = 'Commit'
      AND F.FORECAST > 500000
    )
GROUP BY A.INDUSTRY
ORDER BY TOTAL_PROFIT DESC
;
