-- QUERY DE CONSULTA PARA LA SUMA LOS BENEFICIOS PROMEDIO POR PAIS PARA LAS DOS REGIONES 
SELECT
    REGION,
    SUM(INGRESO_PROM)   	AS SUMA_INGRESO_PROM,
    SUM(UNIDADES_PROM)  	AS SUMA_UNIDADES_PROM,
    SUM(BENEFICIO_PROM) 	AS SUMA_BENEFICIO_PROM
FROM (
    SELECT
        A.REGION 		AS REGION,
        A.COUNTRY 		AS PAIS,
        AVG(S.TOTAL) 		AS INGRESO_PROM,
        AVG(S.UNITS_SOLD) 	AS UNIDADES_PROM,
        AVG(S.PROFIT) 		AS BENEFICIO_PROM
    FROM
        SALES AS S    		JOIN ACCOUNTS AS A
        ON S.ACCOUNT = A.ACCOUNT
    WHERE
        A.REGION IN ('APAC', 'EMEA')
    GROUP BY
        A.REGION,
        A.COUNTRY
) AS REGION_BEN_PROM
GROUP BY REGION
;

-- QUERY PARA COMPROBAR QUE UK NO TIENE VENTAS REGISTRADAS 
SELECT *
    FROM SALES
    WHERE ACCOUNT IN (
    SELECT ACCOUNT
    FROM ACCOUNTS
    WHERE COUNTRY = 'United Kingdom')
;
