-----------------------------------------
--#2. COMPARACION DE RENDIMIENTO POR PAIS EN LAS REGIONES DE APAC Y EMEA
-----------------------------------------
SELECT
    A.REGION 			AS REGION,
    A.COUNTRY 			AS PAIS,
    AVG(S.TOTAL)	 	AS INGRESO_PROM,
    AVG(S.UNITS_SOLD) 		AS UNIDADES_PROM,
    AVG(S.PROFIT) 		AS BENEFICIO_PROM
FROM
    SALES AS S 			JOIN ACCOUNTS AS A
    ON S.ACCOUNT = A.ACCOUNT 
WHERE
    A.REGION IN ('APAC', 'EMEA')
GROUP BY
    A.REGION,
    A.COUNTRY
ORDER BY
    A.REGION,
    BENEFICIO_PROM DESC
;
